// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk6l48HlQuU7iBB-bYoCChabYgQ8hyrYU',
    appId: '1:52229993232:android:8bb8d3145c4d1f8280eb95',
    messagingSenderId: '52229993232',
    projectId: 'let-chat-50962',
    storageBucket: 'let-chat-50962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7awjEtBeNVTJ-a7prJvCuZ6LuoU394zc',
    appId: '1:52229993232:ios:0c745200c0382cbb80eb95',
    messagingSenderId: '52229993232',
    projectId: 'let-chat-50962',
    storageBucket: 'let-chat-50962.appspot.com',
    androidClientId: '52229993232-lviu82e47f2j1e7klh93bdkfeigch9v2.apps.googleusercontent.com',
    iosClientId: '52229993232-6t9v8efi8f1ga23t9hb1m6dfprql92dh.apps.googleusercontent.com',
    iosBundleId: 'com.example.letsChat',
  );
}
